### ISSUE TITLE
Cannot read property 'bitmap' of undefined

### ISSUE THREAD

**Issue by svengau** [tooolbox/node-potrace#8]
Hello, I'm using gatsby-plugin-sharp, and I've got the following error message when generating thumbnails: 

```
TypeError: Cannot read property 'bitmap' of undefined
    at Potrace._processLoadedImage (/Users/svengaubert/workspace/fullstackrocket/gatsby-stripe-netlify-cms-tailwindcss/node_modules/potrace/lib/Potrace.js:1002:35)
    at Jimp.<anonymous> (/Users/svengaubert/workspace/fullstackrocket/gatsby-stripe-netlify-cms-tailwindcss/node_modules/potrace/lib/Potrace.js:1050:14)
    at Timeout._onTimeout (/Users/svengaubert/workspace/fullstackrocket/gatsby-stripe-netlify-cms-tailwindcss/node_modules/@jimp/core/dist/index.js:354:25)
Error: Unsupported MIME type: image/webp
```
After some investigations, it seems JIMP doesn't support webp and sends back the error "Error: Unsupported MIME type: image/webp".  But potrace doesn't check this error, and directly pass a null image to _processLoadedImage, as we can see here:

https://github.com/tooolbox/node-potrace/blob/e1a3d0cfd1b7e408ae273730c5dccd243a91d24f/lib/Potrace.js#L1048

Would it be possible to check the error before calling _processLoadedImage ?

Thanks

**Comment by tooolbox** [comment]
I see the problem you're describing and I don't see why it shouldn't be fixed..  Do you feel up to submitting a PR?

**Comment by mnlfischer** [comment]
is this repo still maintained?

**Comment by tooolbox** [comment]
I don't really have time to maintain this, hence me asking for a PR.  Would be open to adding maintainers who have a vested interest in its survival, perhaps the gatsby folks.
